// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QkvVdTrWu8PvO6d1R1U2RPI_AxC6VNM',
    appId: '1:456501963049:web:d7a8a4df4423bed0ee6f38',
    messagingSenderId: '456501963049',
    projectId: 'horovision-itds283',
    authDomain: 'horovision-itds283.firebaseapp.com',
    databaseURL: 'https://horovision-itds283-default-rtdb.firebaseio.com',
    storageBucket: 'horovision-itds283.appspot.com',
    measurementId: 'G-7J52DFXPHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RqVeN_QlV0wJ6ub-7Pi6AL0_xFeXuK8',
    appId: '1:456501963049:android:18e7c7d589744880ee6f38',
    messagingSenderId: '456501963049',
    projectId: 'horovision-itds283',
    databaseURL: 'https://horovision-itds283-default-rtdb.firebaseio.com',
    storageBucket: 'horovision-itds283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDUCRlOD8_JVMqtkx3wgwoFUQGh2ZAbs',
    appId: '1:456501963049:ios:be34eb2c636c855eee6f38',
    messagingSenderId: '456501963049',
    projectId: 'horovision-itds283',
    databaseURL: 'https://horovision-itds283-default-rtdb.firebaseio.com',
    storageBucket: 'horovision-itds283.appspot.com',
    iosClientId: '456501963049-hvq2ochktr4o9grp5tnodil4ak21orjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.horovisionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDUCRlOD8_JVMqtkx3wgwoFUQGh2ZAbs',
    appId: '1:456501963049:ios:be34eb2c636c855eee6f38',
    messagingSenderId: '456501963049',
    projectId: 'horovision-itds283',
    databaseURL: 'https://horovision-itds283-default-rtdb.firebaseio.com',
    storageBucket: 'horovision-itds283.appspot.com',
    iosClientId: '456501963049-hvq2ochktr4o9grp5tnodil4ak21orjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.horovisionProject',
  );
}
